name: akeneo_api_client
description: A Dart library for interacting with the Akeneo PIM API.
version: 1.0.0
repository: https://github.com/etdvlpr/akeneo_api_client

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  json_annotation: ^4.4.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  lints: ^2.0.0
  test: ^1.21.0
